"""Golden-path RAPP SDK API with no import-time I/O."""

from ._version import VERSION, __version__, __version_info__
from .authority import (
    selected_authority_checkpoint,
    selected_authority_registry,
    selected_authority_trust_policy,
)
from .errors import (
    CacheIntegrityError,
    ProtocolError,
    ProjectProtocolError,
    RappSDKError,
    RingManifestError,
    SpecChainError,
    SpecResolutionError,
)
from .protocol import (
    AuthorityCheckpoint,
    PROTOCOL_VERSION,
    KindFamilyRegistry,
    PersistedHead,
    StreamTrustPolicy,
    VerifiedFrame,
    VerifiedStream,
    build_frame_mapping,
    canonicalize,
    check_frame,
    check_stream,
    strict_json_loads,
    verify_frame,
    verify_stream,
)
from .reports import Diagnostic, DiagnosticStatus, VerificationReport
from .projects import (
    PROJECT_EGG_SCHEMA,
    PROJECT_EGG_VARIANT,
    PROJECT_EVENTS,
    PROJECT_FRAME_KIND,
    PROJECT_FRAME_KINDS,
    ProjectActor,
    ProjectCheckpoint,
    build_project_egg_manifest,
    build_project_frame,
    build_project_rappid,
    pack_project_egg,
    project_egg_address,
    project_kind_registry,
    read_project_egg,
    validate_project_payload,
    verify_project_egg_manifest,
    verify_project_stream,
)
from .resolution import RevisionSource, SpecResolver
from .ring_manifest import (
    RingYardManifest,
    build_default_ring_yard_manifest,
    check_ring_yard_manifest,
    check_ring_yard_manifest_semantics,
    ports_for_cell,
    verify_ring_yard_manifest,
)
from .schemas import (
    RING_YARD_MANIFEST_SCHEMA_ID,
    SPEC_REVISION_SCHEMA_ID,
    read_ring_yard_manifest_schema,
    read_spec_revision_schema,
)
from .spec_chain import (
    ContentLocator,
    RevisionAddress,
    SpecChain,
    SpecRevision,
    build_spec_revision_frame,
)

__all__ = (
    "AuthorityCheckpoint",
    "CacheIntegrityError",
    "ContentLocator",
    "Diagnostic",
    "DiagnosticStatus",
    "KindFamilyRegistry",
    "PROTOCOL_VERSION",
    "PROJECT_EGG_SCHEMA",
    "PROJECT_EGG_VARIANT",
    "PROJECT_EVENTS",
    "PROJECT_FRAME_KIND",
    "PROJECT_FRAME_KINDS",
    "PersistedHead",
    "ProtocolError",
    "ProjectActor",
    "ProjectCheckpoint",
    "ProjectProtocolError",
    "RappSDKError",
    "RING_YARD_MANIFEST_SCHEMA_ID",
    "RevisionAddress",
    "RevisionSource",
    "RingManifestError",
    "RingYardManifest",
    "SPEC_REVISION_SCHEMA_ID",
    "SpecChain",
    "SpecChainError",
    "SpecResolver",
    "SpecResolutionError",
    "SpecRevision",
    "StreamTrustPolicy",
    "VERSION",
    "VerificationReport",
    "VerifiedFrame",
    "VerifiedStream",
    "__version__",
    "__version_info__",
    "build_frame_mapping",
    "build_default_ring_yard_manifest",
    "build_project_egg_manifest",
    "build_project_frame",
    "build_project_rappid",
    "pack_project_egg",
    "project_egg_address",
    "build_spec_revision_frame",
    "canonicalize",
    "check_frame",
    "check_ring_yard_manifest",
    "check_ring_yard_manifest_semantics",
    "check_stream",
    "ports_for_cell",
    "read_ring_yard_manifest_schema",
    "read_spec_revision_schema",
    "project_kind_registry",
    "read_project_egg",
    "selected_authority_checkpoint",
    "selected_authority_registry",
    "selected_authority_trust_policy",
    "strict_json_loads",
    "verify_frame",
    "verify_ring_yard_manifest",
    "validate_project_payload",
    "verify_project_egg_manifest",
    "verify_project_stream",
    "verify_stream",
)
