"""Stable public API for RAPP/1 frames and specification chains.

Importing :mod:`rapp_sdk` performs no I/O, network access, environment reads,
or runtime dependency discovery.
"""

from ._version import VERSION, __version__, __version_info__
from .errors import (
    CacheIntegrityError,
    ProtocolError,
    RappSDKError,
    SpecChainError,
    SpecResolutionError,
)
from .protocol import (
    FRAME_KEYS,
    PARTICLE_SPACE,
    SPEC,
    WAVE_SPACE,
    Frame,
    FrameMapping,
    H,
    Hb,
    JsonValue,
    SignatureVerifier,
    build_frame,
    canonical,
    canonicalize,
    strict_json_loads,
    verify_frame,
    verify_stream,
)
from .schemas import (
    SPEC_REVISION_SCHEMA_ID,
    SPEC_REVISION_SCHEMA_RESOURCE,
    read_spec_revision_schema,
)
from .spec_chain import (
    ByteFetcher,
    ContentAddressedCache,
    GitHubRawSource,
    HTTPSFetcher,
    ImmutableSource,
    MAX_CHAIN_BYTES,
    MAX_SPEC_BYTES,
    RevisionAddress,
    RevisionSelector,
    SpecChain,
    SpecRevision,
    StrPath,
    build_spec_revision_frame,
)

__all__ = (
    "ByteFetcher",
    "CacheIntegrityError",
    "ContentAddressedCache",
    "FRAME_KEYS",
    "Frame",
    "FrameMapping",
    "GitHubRawSource",
    "H",
    "HTTPSFetcher",
    "Hb",
    "ImmutableSource",
    "JsonValue",
    "MAX_CHAIN_BYTES",
    "MAX_SPEC_BYTES",
    "PARTICLE_SPACE",
    "ProtocolError",
    "RappSDKError",
    "RevisionAddress",
    "RevisionSelector",
    "SPEC",
    "SPEC_REVISION_SCHEMA_ID",
    "SPEC_REVISION_SCHEMA_RESOURCE",
    "SignatureVerifier",
    "SpecChain",
    "SpecChainError",
    "SpecResolutionError",
    "SpecRevision",
    "StrPath",
    "VERSION",
    "WAVE_SPACE",
    "__version__",
    "__version_info__",
    "build_frame",
    "build_spec_revision_frame",
    "canonical",
    "canonicalize",
    "read_spec_revision_schema",
    "strict_json_loads",
    "verify_frame",
    "verify_stream",
)
